play_motion:
  controllers: [arm_controller, head_controller, torso_controller]

  motions:
    look_left_1_5:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.5, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_5
        usage: tiago_sim_hospital
        description: 'Look left to 1.5 rad.'

    look_left_1_4:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.4, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_4
        usage: tiago_sim_hospital
        description: 'Look left to 1.4 rad.'

    look_left_1_3:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.3, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_3
        usage: tiago_sim_hospital
        description: 'Look left to 1.3 rad.'

    look_left_1_2:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.2, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_2
        usage: tiago_sim_hospital
        description: 'Look left to 1.2 rad.'

    look_left_1_1:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.1, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_1
        usage: tiago_sim_hospital
        description: 'Look left to 1.1 rad.'

    look_left_1_0:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-1.0, 0]
        time_from_start: 0.0
      meta:
        name: look_left_1_0
        usage: tiago_sim_hospital
        description: 'Look left to 1.0 rad.'

    look_left_0_3:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [-0.3, 0]
        time_from_start: 0.0
      meta:
        name: look_left_0_3
        usage: tiago_sim_hospital
        description: 'Look left to 0.3 rad.'

    look_right_1_5:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [1.5, 0]
        time_from_start: 0.0
      meta:
        name: look_right_1_5
        usage: tiago_sim_hospital
        description: 'Look right to 1.5 rad.'

    look_right_0_3:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.3, 0]
        time_from_start: 0.0
      meta:
        name: look_right_0_3
        usage: tiago_sim_hospital
        description: 'Look right to 0.3 rad.'
